name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Lint Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          # ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          # fetch-depth: 2147483647
      - run: git checkout $GITHUB_HEAD_REF
      - name: Lint PR Title
        run: |
          env && npm install && npm run verify
        working-directory: ./scripts/github-actions/semantic-pull-request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
