name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Lint Title
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # ref: ${{ github.event.pull_request.head.ref }}
          # ref: ${{ github.event.pull_request.head.sha }}
          # fetch-depth: 0
          fetch-depth: 2147483647
      - run: git checkout ${{ env.GITHUB_HEAD_REF }}
      - name: Lint PR Title
        run: |
          env && npm install && npm run verify
        working-directory: .github/workflows/semantic-pull-request/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # use a fork of the GitHub action - we cannot pull in untrusted third party actions
      # see https://github.com/cypress-io/cypress/pull/20091#discussion_r801799647
      # - uses: cypress-io/action-semantic-pull-request@v4
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     validateSingleCommit: true
      #     types: |
      #       breaking      # A breaking change that will require a MVB
      #       dependency    # A change to a dependency that impact the user
      #       deprecation   # A API deprecation notice for users
      #       feat          # A new feature
      #       fix           # A bug or regression fix
      #       misc          # a misc user-facing change, like a UI update, which is not a fix or enhancement to how Cypress works
      #       perf          # A code change that improves performance
      #       chore         # Changes to the build process or auxiliary tools and libraries such as documentation generation
      #       docs          # Documentation only changes
      #       refactor      # A code change that neither fixes a bug nor adds a feature
      #       revert        # Reverts a previous commit"
      #       test          # Adding missing or correcting existing tests
