name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Lint PR Title and Binary Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          fetch-depth: 0
      - run: git checkout $GITHUB_HEAD_REF
      - name: Lint PR Title and Binary Changelog
        uses: actions/github-script@v4
        with:
          script: |
            const { run } = require('./scripts/github-actions/semantic-pull-request')

            await run({ context, core, github })
